### ISSUE TITLE
LzoPigStorage does not use work directory; failed tasks fail whole MapReduce job

### ISSUE THREAD

**Issue by ddaniels** [twitter/elephant-bird#326]
I've been seeing a lot of large jobs that use LzoPigStorage against the S3 filesystem have a single task fail, and then have the entire job fail b/c output was written to the final target.

I think the root cause of this is that LzoPigStorage uses TupleOutputFormat, which extends LzoOutputFormat rather than LzoTextOutputFormat.  LzoOutputFormat (unlike LzoTextOutputFormat) does not use the work directory ( _temporary/_${taskid} ), but rather writes directly to the final output location.  

I think that this is causing the flakiness I'm seeing, where a task that fails mid-way through an S3 write leaves data in the output directory, and then later tasks refuse to run b/c that output already exists, effectively killing the whole MapReduce job.

Is there are reason not to use the work directory here?  Could I either switch LzoPigStorage to use LzoTextOutputFormat or update LzoOutputFormat to use work directories?

**Comment by nellore** [comment]
Did you ever find a solution to this problem, @ddaniels888 ? I'm currently seeing precisely the behavior you described above using `LzoTextOutputFormat`.

**Comment by ddaniels888** [comment]
@nellore It's been a while, but if I recall correctly I did a combination of:

1. Disabling speculative execution
2. [Ensure any output written is fully cleaned up to prevent downstream retry tasks from failing](https://github.com/mortardata/elephant-bird/pull/2)

You might also want [Retry file status (ls) operations, which can fail with FileNotFound due to eventual consistency in S3](https://github.com/mortardata/elephant-bird/pull/1) for good measure.

**Comment by nellore** [comment]
Got it. Thanks!
